### ISSUE TITLE
`and` / `or` keywords with `raise` / `fail`

### ISSUE THREAD

**Issue by smanolloff** [rubocop-hq/ruby-style-guide#415] opened 2015-02-11 11:28 UTC
The idea of banning the `and` & `or` keywords is really cool.

However, there is one specific case in which they may be preferred:

``` ruby
authenticate_user! || fail AuthenticationFailure, 'Invalid credentials'
# SyntaxError: unexpected '\n', expecting :: or '[' or '.'

authenticate_user! or fail AuthenticationFailure, 'Invalid credentials'
# (this works ok)
```

Of course, we we could just use

``` ruby
fail AuthenticationFailure, 'Invalid credentials' unless authenticate_user!
```

... but doesn't it degrade readability?

Is the usage of `and` or `or`, immediately followed by a `raise` or `fail`, justified?
I would be happy if you could share your thoughts!

**Comment by philoserf** [comment] 2015-02-18 06:55
I find the `object.test or fail 'message'` construction is very common in the wild.

**Comment by bbatsov** [comment] 2015-02-18 07:02
> I find the object.test or fail 'message' construction is very common in the wild.

In Perl. :-) Seriously, though - yeah, it's popular to some extent but way more people use modifier `if/unless` for such code.

**Comment by smanolloff** [comment] 2015-02-20 16:28
Sure, i guess that is fine.
But we should not forget that the `if / unless` one-liners are not exactly the same as the boolean operators: 

```ruby
def current_user
  fail 'Authentication failed' unless @current_user ||= authenticate
  @current_user # need to return explicitly
end

def current_user
  @current_user ||= authenticate or fail 'Authentication failed'
end
```

**Comment by luizdamim** [comment] 2015-02-27 12:36
:+1: for allowing `and`/`or` followed by `raise`/`fail`. I use it quite frequently in my codebase.

**Comment by Ajedi32** [comment] 2015-07-10 14:02
I think the real crux of the issue is that `and` and `or` are perfectly fine to use for their intended purpose: as control flow operators. The problems they cause usually occur when people try to use them in place of `||` and `&&` as boolean operators.

Then again though, `if` and `unless` can usually be used in place of `or` and `and`, so idk...

**Comment by bbatsov** [comment] 2015-07-10 14:32
> I think the real crux of the issue is that and and or are perfectly fine to use for their intended purpose: as control flow operators.

Pretty sure those were never intended as flow of control operators. This is something which people came up with to justify their existence. It's pretty clear they were actually added to facilitate a style of programming with less parentheses in it, which is a good or a bad thing, depending who you ask.

**Comment by cheerfulstoic** [comment] 2015-09-26 22:08
Avdi Grimm has a really great (and free) RubyTapas episode about this:

http://devblog.avdi.org/2014/08/26/how-to-use-rubys-english-andor-operators-without-going-nuts/

:+1: on use as flow control operators!

**Comment by pirj** [comment] 2021-02-21 18:30
Duplicate of #730

**Closed by pirj** 2021-02-21 18:30 UTC
